# Generated by Django 6.0 on 2026-01-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bus_busbooking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name_plural': 'Buses'},
        ),
        migrations.RemoveField(
            model_name='bus',
            name='image',
        ),
    ]
