# Generated by Django 5.2.8 on 2026-01-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='hall',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Maintenance', 'Under Maintenance'), ('Reserved', 'Reserved (Priority)')], default='Available', max_length=20),
        ),
    ]
