# Generated by Django 6.0 on 2026-01-12 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_bus_options_remove_bus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='busbooking',
            name='origin',
            field=models.CharField(default='College Campus', max_length=200),
        ),
    ]
