# Generated by Django 6.0 on 2026-01-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_busbooking_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='faculty_in_charge',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
