# Generated by Django 6.0 on 2026-01-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_booking_faculty_in_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='requested_facilities',
            field=models.ManyToManyField(blank=True, to='core.facility'),
        ),
        migrations.AddField(
            model_name='space',
            name='facilities',
            field=models.ManyToManyField(blank=True, related_name='spaces', to='core.facility'),
        ),
    ]
