# Generated by Django 6.0 on 2026-02-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_facility_booking_requested_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='spaces/'),
        ),
    ]
