# Generated by Django 6.0 on 2026-02-09 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_space_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
