# Generated by Django 6.0 on 2026-02-09 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_spacetype_alter_space_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spaces', to='core.spacetype'),
        ),
    ]
