# Generated by Django 6.0 on 2026-02-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_space_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approval_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='auto_expired',
            field=models.BooleanField(default=False),
        ),
    ]
