# Generated by Django 6.0 on 2026-02-17 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_booking_options_alter_booking_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-date', 'start_time', 'resource_type', 'created_at']},
        ),
        migrations.AddField(
            model_name='booking',
            name='resource_name',
            field=models.CharField(blank=True, help_text='Required for External events', max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource_number',
            field=models.CharField(blank=True, help_text='Contact number for coordination', max_length=15),
        ),
        migrations.AddField(
            model_name='booking',
            name='resource_type',
            field=models.CharField(choices=[('Internal', 'Internal (Standard)'), ('External', 'External (High Priority)')], default='Internal', help_text='External events get higher priority in the waitlist.', max_length=10),
        ),
    ]
